# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doufu', '0002_doufu_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doufu',
            name='test_migration',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
    ]
