# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doufu', '0003_doufu_test_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doufu',
            name='test_migration',
        ),
        migrations.AddField(
            model_name='doufu',
            name='raw_material',
            field=models.CharField(default=15, max_length=200),
            preserve_default=False,
        ),
    ]
