# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doufu', '0004_auto_20161013_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='doufu',
            name='introduce',
            field=models.CharField(default=15, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doufu',
            name='methods',
            field=models.CharField(default=15, max_length=1500),
            preserve_default=False,
        ),
    ]
